version: '3'

services:
  bidprentjesdb:
    image: postgres:10-alpine
    hostname: database
    container_name: bidprentjesdb
    volumes:
      - ./initdb.d:/docker-entrypoint-initdb.d
    environment:
      POSTGRES_PASSWORD: Heiligboontje1!
      POSTGRES_USER: DePastoor
      POSTGRES_DB: bidprentjes 

  bidprentjesweb:
    image: bidprentjesweb
    restart: unless-stopped
    links:
      - bidprentjesdb
    ports:
      - 8080:8080
    build:
      context: .
      dockerfile: Dockerfile
    environment:
      PGUSER: DePastoor 
      PGHOST: bidprentjesdb
      PGPASSWORD: Heiligboontje1!
      PGDATABASE: bidprentjes
